version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres_stock
    ports:
      - 5432:5432

    environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
        - POSTGRES_DB=stock_db
